cmake_minimum_required(VERSION 3.20)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
execute_process(COMMAND git ls-files WORKING_DIRECTORY "${ROOT}"
    OUTPUT_VARIABLE FILES RESULT_VARIABLE STATUS OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT STATUS EQUAL 0)
    message(FATAL_ERROR "Cannot inspect the Git publication payload")
endif()
string(REPLACE "\n" ";" FILES "${FILES}")
foreach(FILE IN LISTS FILES)
    if(FILE MATCHES "^(noncleaned_data|desktop|third_party|firmware|data)/"
       OR FILE MATCHES "\\.(zip|pdf|exe|obj|ipch|pdb|mp4|webm|slxc)$")
        message(FATAL_ERROR "Excluded source/generated/large-media path is tracked: ${FILE}")
    endif()
    file(SIZE "${ROOT}/${FILE}" SIZE)
    if(SIZE GREATER 5242880)
        message(FATAL_ERROR "Tracked file exceeds the 5 MiB publication limit: ${FILE}")
    endif()
endforeach()
message(STATUS "Publication payload checked: no excluded paths or files above 5 MiB")
